### ISSUE TITLE
Rename repository?

### ISSUE THREAD

**Issue by jaycedotbin** [sugarykeytone/manjaro-to-arch.sh#21]
Hey,

Have you considered renaming the repository with kebab case?
Something along the lines of `manjaro-to-arch.sh` then adding a
description that says:

> A script for converting a Manjaro installation to
> an Arch installation with a single command.

Something like that, just a recommendation, I think it is much more
memorable and clearly states that it is a shell script???

**Comment by sugarykeytone** [comment]
Oh so like pdf.js which shows it's clearly one of those great libraries which were written in a crap language?

**Comment by jaycedotbin** [comment]
Something like that😆

The roast was unnecessary but yes 🤣

**Comment by sugarykeytone** [comment]
I did it, though I like snake case better cuz it brings the nostalgia of windows 7
